spring:
  application:
    name: gateway
server:
  port: 8080

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

zuul:
  routes:
    base-service:
      path: /base-service/**
    discovery:
      path: /discovery/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://localhost:8761
    server:
      path: /server/**

hystrix:
  command:
    base-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
    discovery:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
