spring:
  application:
    name: gateway
  cloud:
    gateway:
      metrics:
        enabled: true
      routes:
        - id: recipes
          uri: lb://recipes
          predicates:
            - Path=/recipes/**
          filters:
            - StripPrefix=1
server:
  port: 8080

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

management:
  endpoints:
    web:
      exposure:
        include: "health"
